version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: hps-postgres-vector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hps_docs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: